/*
 * lssgkcu.h
 *
 *  Created on: 1 oct. 2017
 *      Author: Ludovic
 */

#ifndef LSSGKCU_IN_H
#define LSSGKCU_IN_H

#include "tch.h"

/*** LSMCU -> LSSGKCU ***/

// Commands list.
typedef enum {
	// Bytes 0 to 100 are reserved for coding CP pressure*10 in bars.
	LSSGKCU_IN_ZBA_ON = 101,
	LSSGKCU_IN_ZBA_OFF,
	LSSGKCU_IN_RSEC_ON,
	LSSGKCU_IN_RSEC_OFF,
	LSSGKCU_IN_ZDV_ON,
	LSSGKCU_IN_ZDV_OFF,
	LSSGKCU_IN_ZPT_BACK_UP,
	LSSGKCU_IN_ZPT_BACK_DOWN,
	LSSGKCU_IN_ZPT_FRONT_UP,
	LSSGKCU_IN_ZPT_FRONT_DOWN,
	LSSGKCU_IN_ZDJ_OFF,
	LSSGKCU_IN_ZEN_ON,
	LSSGKCU_IN_ZCA_ON,
	LSSGKCU_IN_ZCA_OFF,
	LSSGKCU_IN_ZCD_ON,
	LSSGKCU_IN_ZCD_OFF,
	LSSGKCU_IN_FPB_ON,
	LSSGKCU_IN_FPB_OFF,
	LSSGKCU_IN_FPB_APPLY,
	LSSGKCU_IN_FPB_NEUTRAL,
	LSSGKCU_IN_FPB_RELEASE,
	LSSGKCU_IN_BPGD,
	LSSGKCU_IN_ZVM_ON,
	LSSGKCU_IN_ZVM_OFF,
	LSSGKCU_IN_INV_FORWARD,
	LSSGKCU_IN_INV_NEUTRAL,
	LSSGKCU_IN_INV_BACKWARD,
	LSSGKCU_IN_MP_0,
	LSSGKCU_IN_MP_T_MORE,
	LSSGKCU_IN_MP_T_LESS,
	LSSGKCU_IN_MP_F_MORE,
	LSSGKCU_IN_MP_F_LESS,
	LSSGKCU_IN_MP_PR,
	LSSGKCU_IN_MP_P,
	LSSGKCU_IN_FD_APPLY,
	LSSGKCU_IN_FD_NEUTRAL,
	LSSGKCU_IN_FD_RELEASE,
	LSSGKCU_IN_BPURG,
	LSSGKCU_IN_S_HIGH_TONE,
	LSSGKCU_IN_S_LOW_TONE,
	LSSGKCU_IN_S_NEUTRAL,
	LSSGKCU_IN_BPEV_ON,
	LSSGKCU_IN_BPEV_OFF,
	LSSGKCU_IN_BPSA_ON,
	LSSGKCU_IN_BPSA_OFF,
	LSSGKCU_IN_ZFG_ON,
	LSSGKCU_IN_ZFG_OFF,
	LSSGKCU_IN_ZFD_ON,
	LSSGKCU_IN_ZFD_OFF,
	LSSGKCU_IN_ZPR_ON,
	LSSGKCU_IN_ZPR_OFF,
	LSSGKCU_IN_ZLFRG_ON,
	LSSGKCU_IN_ZLFRG_OFF,
	LSSGKCU_IN_ZLFRD_ON,
	LSSGKCU_IN_ZLFRD_OFF,
	LSSGKCU_IN_ACSF_ON,
	LSSGKCU_IN_ACSF_OFF,
	LSSGKCU_IN_KVB_BPVAL_ON,
	LSSGKCU_IN_KVB_BPVAL_OFF,
	LSSGKCU_IN_KVB_BPMV_ON,
	LSSGKCU_IN_KVB_BPMV_OFF,
	LSSGKCU_IN_KVB_BPFC_ON,
	LSSGKCU_IN_KVB_BPFC_OFF,
	LSSGKCU_IN_KVB_BPTEST_ON,
	LSSGKCU_IN_KVB_BPTEST_OFF,
	LSSGKCU_IN_KVB_BPSF_ON,
	LSSGKCU_IN_KVB_BPSF_OFF
} LSMCU_To_LSSGKCU;

// CP pressure.
#define CP_SUPPLY_TIME_MS 	125000 // Must correspond to the length of 'regulationMax.wav' sound (in ms).
#define CP_HYSTERESIS_LOW 	7800 // In mbars.
#define CP_HYSTERESIS_HIGH 	9000 // In mbars.
#define CP_MAXIMUM_VALUE 	9500 // In mbars.
#define CP_SUPPLY_SPEED 	((CP_HYSTERESIS_HIGH) / (CP_SUPPLY_TIME)) // In mbars/ms.

/*** LSSGKCU -> LSMCU ***/

// Command list.
typedef enum {
	// Bytes 0 to TCH_SPEED_MAX_KMH are reserved for coding speed in km/h.
	// KVB common.
	LSSGKCU_OUT_KVB_ALL_OFF = TCH_SPEED_MAX_KMH + 1,
	// KVB lights.
	LSSGKCU_OUT_KVB_LVAL_BLINK,
	LSSGKCU_OUT_KVB_LVAL_ON,
	LSSGKCU_OUT_KVB_LVAL_OFF,
	LSSGKCU_OUT_KVB_LMV_ON,
	LSSGKCU_OUT_KVB_LMV_OFF,
	LSSGKCU_OUT_KVB_LFC_ON,
	LSSGKCU_OUT_KVB_LFC_OFF,
	LSSGKCU_OUT_KVB_LV_ON,
	LSSGKCU_OUT_KVB_LV_OFF,
	LSSGKCU_OUT_KVB_LFU_ON,
	LSSGKCU_OUT_KVB_LFU_OFF,
	LSSGKCU_OUT_KVB_LPS_ON,
	LSSGKCU_OUT_KVB_LPS_OFF,
	LSSGKCU_OUT_KVB_LSSF_BLINK,
	LSSGKCU_OUT_KVB_LSSF_ON,
	LSSGKCU_OUT_KVB_LSSF_OFF,
	// KVB 7-segments displays.
	LSSGKCU_OUT_KVB_YG_OFF,
	LSSGKCU_OUT_KVB_YG_PA400,
	LSSGKCU_OUT_KVB_YG_UC512,
	LSSGKCU_OUT_KVB_YG_888,
	LSSGKCU_OUT_KVB_YG_DASH,
	LSSGKCU_OUT_KVB_G_B,
	LSSGKCU_OUT_KVB_Y_B,
	LSSGKCU_OUT_KVB_G_P,
	LSSGKCU_OUT_KVB_Y_P,
	LSSGKCU_OUT_KVB_G_L,
	LSSGKCU_OUT_KVB_Y_L,
	LSSGKCU_OUT_KVB_G_00,
	LSSGKCU_OUT_KVB_Y_00,
	LSSGKCU_OUT_KVB_G_000,
	LSSGKCU_OUT_KVB_Y_000,
} LSSGKCU_To_LSMCU;

/*** LSSGKCU functions ***/

void LSSGKCU_Init(void);
void LSSGKCU_FillRxBuffer(unsigned char at_cmd);
void LSSGKCU_Send(unsigned char at_cmd);
void LSSGKCU_Task(void);

#endif /* LSSGKCU_IN_H */
